apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replicaset-2
  labels:
    app: frontend-replica
spec:
  selector:
    matchLabels:
      env: production
  replicas: 3
  template:
    metadata:
      name: nginx_pod
      labels:
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx
        - name: redis
          image: redis
