apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: voting-app
    app: redis-db
spec:
  containers:
  - name: redis-db
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "50Mi"
        cpu: "200m"
    ports:
      - containerPort: 6379
