apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: voting-app
    app: worker-app
spec:
  containers:
  - name: worker-app
    image: kodekloud/examplevotingapp_worker:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "50Mi"
        cpu: "200m"
