apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: voting-app
    app: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app
      app: postgres-db
  template:
    metadata:
      name: postgres-pod
      labels:
        name: voting-app
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "50Mi"
            cpu: "50m"
        ports:
          - containerPort: 5432
        env: 
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
