apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: voting-app
    app: postgres-clusterip-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: voting-app
    app: postgres-db