apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: voting-app
    app: redis-clusterip-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: voting-app
    app: redis-db