apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: voting-app
    app: result-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app
      app: result-frontend
  template:
    metadata:
      name: result-app-pod
      labels:
        name: voting-app
        app: result-frontend
    spec:
      containers:
      - name: result-app
        image: kodekloud/examplevotingapp_result:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "50Mi"
            cpu: "200m"
        ports:
          - containerPort: 80

