apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    name: voting-app
    app: result-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30005
      targetPort: 80
  selector:
    name: voting-app
    app: result-frontend