apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app
    app: voting-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30004
      targetPort: 80
  selector:
    name: voting-app
    app: voting-frontend